spring.application.name=webapp-1

# ==============================
# PostgreSQL接続設定
# ==============================

# PostgreSQLドライバー
spring.datasource.driver-class-name=org.postgresql.Driver

# 接続先データベース
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb

# PostgreSQLユーザー
spring.datasource.username=springuser

# PostgreSQLパスワード
spring.datasource.password=p@ss


# ==============================
# SQL初期化
# ==============================

# schema.sqlを起動時に実行
spring.sql.init.mode=always


# ==============================
# MyBatis
# ==============================

# MapperのSQLをコンソールに表示
logging.level.com.example.demo.repository=DEBUG